<?php

header("Content-Type: application/json");

require_once 'config/db_connect.php';

$order_no    = $_GET['order_no'];
$customer_id = $_GET['customer_id'];

$sql = "DELETE FROM ORDERPRODUCTS 
        WHERE ORDER_NO = :order_no";

$stid = oci_parse($conn, $sql);
oci_bind_by_name($stid, ":order_no", $order_no);

if (oci_execute($stid)) {

    $sqlDeleteOrder = "DELETE FROM ORDERS 
                       WHERE ORDER_NO = :order_no 
                       AND CUSTOMER_ID = :customer_id";
    $stidDeleteOrder = oci_parse($conn, $sqlDeleteOrder);
    oci_bind_by_name($stidDeleteOrder, ":order_no",    $order_no);
    oci_bind_by_name($stidDeleteOrder, ":customer_id", $customer_id);
    oci_execute($stidDeleteOrder);
    oci_free_statement($stidDeleteOrder);

    $sqlMaxNo = "SELECT MAX(ORDER_NO) + 1 AS NEXT_ID FROM ORDERS";
    $stNoMax  = oci_parse($conn, $sqlMaxNo);
    oci_execute($stNoMax);
    $rowMax = oci_fetch_assoc($stNoMax);
    $nextId = (int)$rowMax['NEXT_ID'];

    $sqlRestartOrderNum  = "ALTER TABLE ORDERS 
                            MODIFY ORDER_NO GENERATED BY DEFAULT AS IDENTITY (START WITH $nextId)";
    $stidRestartOrderNum = oci_parse($conn, $sqlRestartOrderNum);
    oci_execute($stidRestartOrderNum);
    oci_free_statement($stidRestartOrderNum);

    echo json_encode("Customer order deleted successfully");

} else {
    $e = oci_error($stid);
    echo json_encode("Failed to delete customer order: " . $e['message']);
}

oci_free_statement($stid);
oci_close($conn);

?>