<?php
header("Content-Type: application/json");
require_once 'config/db_connect.php';

if (!$conn) {
    http_response_code(500);
    echo json_encode("Database connection failed");
    exit;
}

$productId = isset($_GET['product_id']) ? (int)$_GET['product_id'] : 0;

if ($productId === 0) {
    http_response_code(400);
    echo json_encode("Missing or invalid product_id");
    exit;
}

$sqlDelete = "DELETE FROM PRODUCT WHERE PRODUCT_ID = :product_id";
$stid = oci_parse($conn, $sqlDelete);

oci_bind_by_name($stid, ":product_id", $productId);

if (oci_execute($stid, OCI_COMMIT_ON_SUCCESS)) {
    $sqlMaxId = "SELECT MAX(PRODUCT_ID) AS MAX_ID FROM PRODUCT";
    $stidMax = oci_parse($conn, $sqlMaxId);
    oci_execute($stidMax);
    $row = oci_fetch_assoc($stidMax);
    $nextId = ((int)$row['MAX_ID']) + 1;
    oci_free_statement($stidMax);

    $sqlRestart = "ALTER TABLE PRODUCT MODIFY PRODUCT_ID GENERATED BY DEFAULT AS IDENTITY (START WITH " . $nextId . ")";
    $stidRestart = oci_parse($conn, $sqlRestart);
    oci_execute($stidRestart);
    oci_free_statement($stidRestart);

    echo json_encode("Vendor Product deleted successfully");
} else {
    $e = oci_error($stid);
    http_response_code(500);
    echo json_encode("Failed to delete vendor product: " . $e['message']);
}

oci_free_statement($stid);
oci_close($conn);
?>
